TRIP = {
    "destination": "Tokyo & Kyoto, Japan",
    "dates": {"start": "Oct 14", "end": "Oct 24", "nights": 10},
    "travelers": 3,
    "style": "Standard",
    "must_haves": ["Michelin sushi", "Fushimi Inari"],
    "context_badge": "Oct peak foliage",
}

FLIGHTS = []

HOTELS = [
    {
        "tier": "Budget",
        "name": "Book and Bed Tokyo",
        "neighborhood": "Shinjuku · Kabukicho",
        "stars": 4,
        "price_jpy": 6800,
        "price_usd": 45,
        "amenities": ["Bookshelf capsule", "Free WiFi"],
        "transit": "3 min · Shinjuku Stn",
        "selected": False,
        "tier_color": "#059669",
    },
    {
        "tier": "Standard",
        "name": "Andaz Tokyo Toranomon",
        "neighborhood": "Toranomon · Minato-ku",
        "stars": 5,
        "price_jpy": 68000,
        "price_usd": 450,
        "amenities": ["Rooftop bar", "Spa"],
        "transit": "5 min · Toranomon Hills",
        "selected": True,
        "tier_color": "#7c3aed",
    },
    {
        "tier": "Luxury",
        "name": "Aman Tokyo",
        "neighborhood": "Otemachi · Chiyoda-ku",
        "stars": 5,
        "price_jpy": 145000,
        "price_usd": 960,
        "amenities": ["Onsen spa", "25m pool"],
        "transit": "Direct · Otemachi Stn",
        "selected": False,
        "tier_color": "#f59e0b",
    },
]

ACTIVITIES = [
    {
        "name": "TeamLab Planets",
        "category": "Immersive art",
        "duration": "2 hrs",
        "price_jpy": 3200,
        "score": 98,
        "badge": "Top pick",
        "badge_color": "#7c3aed",
        "tags": ["Culture", "Immersive", "Nightlife"],
        "description": "Water mirror rooms unlike anything on earth — perfect for your visual travel style.",
        "saved": True,
    },
    {
        "name": "Golden Gai crawl",
        "category": "Nightlife",
        "duration": "3 hrs",
        "price_jpy": 3500,
        "score": 94,
        "badge": "Hidden gem",
        "badge_color": "#059669",
        "tags": ["Nightlife", "Shinjuku"],
        "description": "A maze of 200+ tiny bars, each with its own personality. Ideal for your nightlife must-have.",
        "saved": True,
    },
    {
        "name": "Meiji Shrine at sunrise",
        "category": "Culture",
        "duration": "2 hrs",
        "price_jpy": 0,
        "score": 91,
        "badge": "Hidden gem",
        "badge_color": "#059669",
        "tags": ["Culture", "Free"],
        "description": "Walk through the cedar forest at dawn before the crowds arrive. Entirely free.",
        "saved": False,
    },
    {
        "name": "Tsukiji Outer Market",
        "category": "Food & drink",
        "duration": "1.5 hrs",
        "price_jpy": 3000,
        "score": 95,
        "badge": "Must try",
        "badge_color": "#dc2626",
        "tags": ["Food", "Morning"],
        "description": "Fresh tamagoyaki, uni, and premium tuna — the best breakfast in Tokyo.",
        "saved": True,
    },
    {
        "name": "Hakone onsen day trip",
        "category": "Wellness",
        "duration": "Full day",
        "price_jpy": 8800,
        "score": 88,
        "badge": "Splurge",
        "badge_color": "#d97706",
        "tags": ["Luxury", "Nature"],
        "description": "Soak in volcanic springs with Mt. Fuji views. Worth every yen.",
        "saved": False,
    },
    {
        "name": "Shibuya Sky deck",
        "category": "Views",
        "duration": "1 hr",
        "price_jpy": 2000,
        "score": 82,
        "badge": "Popular",
        "badge_color": "#0891b2",
        "tags": ["Views", "Photography"],
        "description": "360° rooftop with Shibuya crossing far below. Best at dusk.",
        "saved": True,
    },
]

AI_PICKS = [
    {
        "type": "Cost optimization",
        "icon": "✈",
        "title": "Flight savings · $560 found",
        "body": "Compare one-stop economy routes against premium cabins before booking. Lower flight spend can free up budget for extra nights or better local experiences.",
        "cta": "Switch flight",
        "accent": "#059669",
    },
    {
        "type": "Timing optimization",
        "icon": "📅",
        "title": "Better dates · save 18%",
        "body": "Compare adjacent travel dates before booking. Similar weather and itinerary quality can come with lower fares.",
        "cta": "Adjust dates",
        "accent": "#7c3aed",
    },
    {
        "type": "Experience upgrade",
        "icon": "🏨",
        "title": "Hotel swap · unique experience",
        "body": "Swap Andaz night 3 for Book and Bed Tokyo — the bookshelf capsule in Shinjuku. One-tenth of the price, far more memorable. Put the $180 saved toward Sushi Saito.",
        "cta": "Swap hotel",
        "accent": "#d97706",
    },
]

ITINERARY_PREVIEW = [
    {
        "date": "Monday, Oct 14",
        "weather": "22°C · Partly cloudy",
        "weather_icon": "🌤",
        "events": [
            {"time": "07:30", "period": "MORNING", "title": "Selected flight departs SFO", "detail": "Confirm live fare, cabin, and routing before booking", "color": "#1e1b4b"},
            {"time": "14:10", "period": "AFTERNOON", "title": "Narita Express → Shinjuku", "detail": "90 min · ¥3,070 · IC Card", "color": "#0c4a6e"},
            {"time": "16:00", "period": "AFTERNOON", "title": "Check in — Andaz Tokyo", "detail": "Toranomon Hills · 52nd floor", "color": "#4c1d95"},
            {"time": "20:00", "period": "EVENING", "title": "Sushi Saito · omakase", "detail": "Michelin 3★ · ¥33,000 pp · confirmed", "color": "#7c2d12", "pinned": True},
        ],
    },
    {
        "date": "Tuesday, Oct 15",
        "weather": "21°C · Sunny",
        "weather_icon": "☀",
        "events": [
            {"time": "06:30", "period": "MORNING", "title": "Meiji Shrine at sunrise", "detail": "Culture · Free · 2 hrs", "color": "#14532d"},
            {"time": "09:00", "period": "MORNING", "title": "Tsukiji Outer Market", "detail": "Food · ~¥3,000 · 1.5 hrs", "color": "#7c2d12"},
            {"time": "14:00", "period": "AFTERNOON", "title": "TeamLab Planets", "detail": "Immersive art · ¥3,200 · 2 hrs", "color": "#1e1b4b"},
            {"time": "20:00", "period": "EVENING", "title": "Golden Gai crawl", "detail": "Nightlife · Shinjuku · ~¥5,000", "color": "#4c1d95"},
        ],
    },
]
